#encoding: utf-8
from util import *
import re

def crawl_sitemap(url):
    sitemap = download(url)
    links = re.findall('<loc>(.*?)</loc>', sitemap)
    for link in links:
        print link

if __name__ == "__main__":
    crawl_sitemap(base_url+"/sitemap.xml")

"""
Downloading:  http://example.webscraping.com/places/default/sitemap.xml
http://web-scraping.appspot.com/places/default/view/Afghanistan-1
http://web-scraping.appspot.com/places/default/view/Aland-Islands-2
http://web-scraping.appspot.com/places/default/view/Albania-3
http://web-scraping.appspot.com/places/default/view/Algeria-4
http://web-scraping.appspot.com/places/default/view/American-Samoa-5
http://web-scraping.appspot.com/places/default/view/Andorra-6
http://web-scraping.appspot.com/places/default/view/Angola-7
http://web-scraping.appspot.com/places/default/view/Anguilla-8
http://web-scraping.appspot.com/places/default/view/Antarctica-9
http://web-scraping.appspot.com/places/default/view/Antigua-and-Barbuda-10
http://web-scraping.appspot.com/places/default/view/Argentina-11
http://web-scraping.appspot.com/places/default/view/Armenia-12
http://web-scraping.appspot.com/places/default/view/Aruba-13
http://web-scraping.appspot.com/places/default/view/Australia-14
http://web-scraping.appspot.com/places/default/view/Austria-15
http://web-scraping.appspot.com/places/default/view/Azerbaijan-16
http://web-scraping.appspot.com/places/default/view/Bahamas-17
http://web-scraping.appspot.com/places/default/view/Bahrain-18
http://web-scraping.appspot.com/places/default/view/Bangladesh-19
http://web-scraping.appspot.com/places/default/view/Barbados-20
http://web-scraping.appspot.com/places/default/view/Belarus-21
http://web-scraping.appspot.com/places/default/view/Belgium-22
http://web-scraping.appspot.com/places/default/view/Belize-23
http://web-scraping.appspot.com/places/default/view/Benin-24
http://web-scraping.appspot.com/places/default/view/Bermuda-25
http://web-scraping.appspot.com/places/default/view/Bhutan-26
http://web-scraping.appspot.com/places/default/view/Bolivia-27
http://web-scraping.appspot.com/places/default/view/Bonaire-Saint-Eustatius-and-Saba-28
http://web-scraping.appspot.com/places/default/view/Bosnia-and-Herzegovina-29
http://web-scraping.appspot.com/places/default/view/Botswana-30
http://web-scraping.appspot.com/places/default/view/Bouvet-Island-31
http://web-scraping.appspot.com/places/default/view/Brazil-32
http://web-scraping.appspot.com/places/default/view/British-Indian-Ocean-Territory-33
http://web-scraping.appspot.com/places/default/view/British-Virgin-Islands-34
http://web-scraping.appspot.com/places/default/view/Brunei-35
http://web-scraping.appspot.com/places/default/view/Bulgaria-36
http://web-scraping.appspot.com/places/default/view/Burkina-Faso-37
http://web-scraping.appspot.com/places/default/view/Burundi-38
http://web-scraping.appspot.com/places/default/view/Cambodia-39
http://web-scraping.appspot.com/places/default/view/Cameroon-40
http://web-scraping.appspot.com/places/default/view/Canada-41
http://web-scraping.appspot.com/places/default/view/Cape-Verde-42
http://web-scraping.appspot.com/places/default/view/Cayman-Islands-43
http://web-scraping.appspot.com/places/default/view/Central-African-Republic-44
http://web-scraping.appspot.com/places/default/view/Chad-45
http://web-scraping.appspot.com/places/default/view/Chile-46
http://web-scraping.appspot.com/places/default/view/China-47
http://web-scraping.appspot.com/places/default/view/Christmas-Island-48
http://web-scraping.appspot.com/places/default/view/Cocos-Islands-49
http://web-scraping.appspot.com/places/default/view/Colombia-50
http://web-scraping.appspot.com/places/default/view/Comoros-51
http://web-scraping.appspot.com/places/default/view/Cook-Islands-52
http://web-scraping.appspot.com/places/default/view/Costa-Rica-53
http://web-scraping.appspot.com/places/default/view/Croatia-54
http://web-scraping.appspot.com/places/default/view/Cuba-55
http://web-scraping.appspot.com/places/default/view/Curacao-56
http://web-scraping.appspot.com/places/default/view/Cyprus-57
http://web-scraping.appspot.com/places/default/view/Czech-Republic-58
http://web-scraping.appspot.com/places/default/view/Democratic-Republic-of-the-Congo-59
http://web-scraping.appspot.com/places/default/view/Denmark-60
http://web-scraping.appspot.com/places/default/view/Djibouti-61
http://web-scraping.appspot.com/places/default/view/Dominica-62
http://web-scraping.appspot.com/places/default/view/Dominican-Republic-63
http://web-scraping.appspot.com/places/default/view/East-Timor-64
http://web-scraping.appspot.com/places/default/view/Ecuador-65
http://web-scraping.appspot.com/places/default/view/Egypt-66
http://web-scraping.appspot.com/places/default/view/El-Salvador-67
http://web-scraping.appspot.com/places/default/view/Equatorial-Guinea-68
http://web-scraping.appspot.com/places/default/view/Eritrea-69
http://web-scraping.appspot.com/places/default/view/Estonia-70
http://web-scraping.appspot.com/places/default/view/Ethiopia-71
http://web-scraping.appspot.com/places/default/view/Falkland-Islands-72
http://web-scraping.appspot.com/places/default/view/Faroe-Islands-73
http://web-scraping.appspot.com/places/default/view/Fiji-74
http://web-scraping.appspot.com/places/default/view/Finland-75
http://web-scraping.appspot.com/places/default/view/France-76
http://web-scraping.appspot.com/places/default/view/French-Guiana-77
http://web-scraping.appspot.com/places/default/view/French-Polynesia-78
http://web-scraping.appspot.com/places/default/view/French-Southern-Territories-79
http://web-scraping.appspot.com/places/default/view/Gabon-80
http://web-scraping.appspot.com/places/default/view/Gambia-81
http://web-scraping.appspot.com/places/default/view/Georgia-82
http://web-scraping.appspot.com/places/default/view/Germany-83
http://web-scraping.appspot.com/places/default/view/Ghana-84
http://web-scraping.appspot.com/places/default/view/Gibraltar-85
http://web-scraping.appspot.com/places/default/view/Greece-86
http://web-scraping.appspot.com/places/default/view/Greenland-87
http://web-scraping.appspot.com/places/default/view/Grenada-88
http://web-scraping.appspot.com/places/default/view/Guadeloupe-89
http://web-scraping.appspot.com/places/default/view/Guam-90
http://web-scraping.appspot.com/places/default/view/Guatemala-91
http://web-scraping.appspot.com/places/default/view/Guernsey-92
http://web-scraping.appspot.com/places/default/view/Guinea-93
http://web-scraping.appspot.com/places/default/view/Guinea-Bissau-94
http://web-scraping.appspot.com/places/default/view/Guyana-95
http://web-scraping.appspot.com/places/default/view/Haiti-96
http://web-scraping.appspot.com/places/default/view/Heard-Island-and-McDonald-Islands-97
http://web-scraping.appspot.com/places/default/view/Honduras-98
http://web-scraping.appspot.com/places/default/view/Hong-Kong-99
http://web-scraping.appspot.com/places/default/view/Hungary-100
http://web-scraping.appspot.com/places/default/view/Iceland-101
http://web-scraping.appspot.com/places/default/view/India-102
http://web-scraping.appspot.com/places/default/view/Indonesia-103
http://web-scraping.appspot.com/places/default/view/Iran-104
http://web-scraping.appspot.com/places/default/view/Iraq-105
http://web-scraping.appspot.com/places/default/view/Ireland-106
http://web-scraping.appspot.com/places/default/view/Isle-of-Man-107
http://web-scraping.appspot.com/places/default/view/Israel-108
http://web-scraping.appspot.com/places/default/view/Italy-109
http://web-scraping.appspot.com/places/default/view/Ivory-Coast-110
http://web-scraping.appspot.com/places/default/view/Jamaica-111
http://web-scraping.appspot.com/places/default/view/Japan-112
http://web-scraping.appspot.com/places/default/view/Jersey-113
http://web-scraping.appspot.com/places/default/view/Jordan-114
http://web-scraping.appspot.com/places/default/view/Kazakhstan-115
http://web-scraping.appspot.com/places/default/view/Kenya-116
http://web-scraping.appspot.com/places/default/view/Kiribati-117
http://web-scraping.appspot.com/places/default/view/Kosovo-118
http://web-scraping.appspot.com/places/default/view/Kuwait-119
http://web-scraping.appspot.com/places/default/view/Kyrgyzstan-120
http://web-scraping.appspot.com/places/default/view/Laos-121
http://web-scraping.appspot.com/places/default/view/Latvia-122
http://web-scraping.appspot.com/places/default/view/Lebanon-123
http://web-scraping.appspot.com/places/default/view/Lesotho-124
http://web-scraping.appspot.com/places/default/view/Liberia-125
http://web-scraping.appspot.com/places/default/view/Libya-126
http://web-scraping.appspot.com/places/default/view/Liechtenstein-127
http://web-scraping.appspot.com/places/default/view/Lithuania-128
http://web-scraping.appspot.com/places/default/view/Luxembourg-129
http://web-scraping.appspot.com/places/default/view/Macao-130
http://web-scraping.appspot.com/places/default/view/Macedonia-131
http://web-scraping.appspot.com/places/default/view/Madagascar-132
http://web-scraping.appspot.com/places/default/view/Malawi-133
http://web-scraping.appspot.com/places/default/view/Malaysia-134
http://web-scraping.appspot.com/places/default/view/Maldives-135
http://web-scraping.appspot.com/places/default/view/Mali-136
http://web-scraping.appspot.com/places/default/view/Malta-137
http://web-scraping.appspot.com/places/default/view/Marshall-Islands-138
http://web-scraping.appspot.com/places/default/view/Martinique-139
http://web-scraping.appspot.com/places/default/view/Mauritania-140
http://web-scraping.appspot.com/places/default/view/Mauritius-141
http://web-scraping.appspot.com/places/default/view/Mayotte-142
http://web-scraping.appspot.com/places/default/view/Mexico-143
http://web-scraping.appspot.com/places/default/view/Micronesia-144
http://web-scraping.appspot.com/places/default/view/Moldova-145
http://web-scraping.appspot.com/places/default/view/Monaco-146
http://web-scraping.appspot.com/places/default/view/Mongolia-147
http://web-scraping.appspot.com/places/default/view/Montenegro-148
http://web-scraping.appspot.com/places/default/view/Montserrat-149
http://web-scraping.appspot.com/places/default/view/Morocco-150
http://web-scraping.appspot.com/places/default/view/Mozambique-151
http://web-scraping.appspot.com/places/default/view/Myanmar-152
http://web-scraping.appspot.com/places/default/view/Namibia-153
http://web-scraping.appspot.com/places/default/view/Nauru-154
http://web-scraping.appspot.com/places/default/view/Nepal-155
http://web-scraping.appspot.com/places/default/view/Netherlands-156
http://web-scraping.appspot.com/places/default/view/Netherlands-Antilles-157
http://web-scraping.appspot.com/places/default/view/New-Caledonia-158
http://web-scraping.appspot.com/places/default/view/New-Zealand-159
http://web-scraping.appspot.com/places/default/view/Nicaragua-160
http://web-scraping.appspot.com/places/default/view/Niger-161
http://web-scraping.appspot.com/places/default/view/Nigeria-162
http://web-scraping.appspot.com/places/default/view/Niue-163
http://web-scraping.appspot.com/places/default/view/Norfolk-Island-164
http://web-scraping.appspot.com/places/default/view/North-Korea-165
http://web-scraping.appspot.com/places/default/view/Northern-Mariana-Islands-166
http://web-scraping.appspot.com/places/default/view/Norway-167
http://web-scraping.appspot.com/places/default/view/Oman-168
http://web-scraping.appspot.com/places/default/view/Pakistan-169
http://web-scraping.appspot.com/places/default/view/Palau-170
http://web-scraping.appspot.com/places/default/view/Palestinian-Territory-171
http://web-scraping.appspot.com/places/default/view/Panama-172
http://web-scraping.appspot.com/places/default/view/Papua-New-Guinea-173
http://web-scraping.appspot.com/places/default/view/Paraguay-174
http://web-scraping.appspot.com/places/default/view/Peru-175
http://web-scraping.appspot.com/places/default/view/Philippines-176
http://web-scraping.appspot.com/places/default/view/Pitcairn-177
http://web-scraping.appspot.com/places/default/view/Poland-178
http://web-scraping.appspot.com/places/default/view/Portugal-179
http://web-scraping.appspot.com/places/default/view/Puerto-Rico-180
http://web-scraping.appspot.com/places/default/view/Qatar-181
http://web-scraping.appspot.com/places/default/view/Republic-of-the-Congo-182
http://web-scraping.appspot.com/places/default/view/Reunion-183
http://web-scraping.appspot.com/places/default/view/Romania-184
http://web-scraping.appspot.com/places/default/view/Russia-185
http://web-scraping.appspot.com/places/default/view/Rwanda-186
http://web-scraping.appspot.com/places/default/view/Saint-Barthelemy-187
http://web-scraping.appspot.com/places/default/view/Saint-Helena-188
http://web-scraping.appspot.com/places/default/view/Saint-Kitts-and-Nevis-189
http://web-scraping.appspot.com/places/default/view/Saint-Lucia-190
http://web-scraping.appspot.com/places/default/view/Saint-Martin-191
http://web-scraping.appspot.com/places/default/view/Saint-Pierre-and-Miquelon-192
http://web-scraping.appspot.com/places/default/view/Saint-Vincent-and-the-Grenadines-193
http://web-scraping.appspot.com/places/default/view/Samoa-194
http://web-scraping.appspot.com/places/default/view/San-Marino-195
http://web-scraping.appspot.com/places/default/view/Sao-Tome-and-Principe-196
http://web-scraping.appspot.com/places/default/view/Saudi-Arabia-197
http://web-scraping.appspot.com/places/default/view/Senegal-198
http://web-scraping.appspot.com/places/default/view/Serbia-199
http://web-scraping.appspot.com/places/default/view/Serbia-and-Montenegro-200
http://web-scraping.appspot.com/places/default/view/Seychelles-201
http://web-scraping.appspot.com/places/default/view/Sierra-Leone-202
http://web-scraping.appspot.com/places/default/view/Singapore-203
http://web-scraping.appspot.com/places/default/view/Sint-Maarten-204
http://web-scraping.appspot.com/places/default/view/Slovakia-205
http://web-scraping.appspot.com/places/default/view/Slovenia-206
http://web-scraping.appspot.com/places/default/view/Solomon-Islands-207
http://web-scraping.appspot.com/places/default/view/Somalia-208
http://web-scraping.appspot.com/places/default/view/South-Africa-209
http://web-scraping.appspot.com/places/default/view/South-Georgia-and-the-South-Sandwich-Islands-210
http://web-scraping.appspot.com/places/default/view/South-Korea-211
http://web-scraping.appspot.com/places/default/view/South-Sudan-212
http://web-scraping.appspot.com/places/default/view/Spain-213
http://web-scraping.appspot.com/places/default/view/Sri-Lanka-214
http://web-scraping.appspot.com/places/default/view/Sudan-215
http://web-scraping.appspot.com/places/default/view/Suriname-216
http://web-scraping.appspot.com/places/default/view/Svalbard-and-Jan-Mayen-217
http://web-scraping.appspot.com/places/default/view/Swaziland-218
http://web-scraping.appspot.com/places/default/view/Sweden-219
http://web-scraping.appspot.com/places/default/view/Switzerland-220
http://web-scraping.appspot.com/places/default/view/Syria-221
http://web-scraping.appspot.com/places/default/view/Taiwan-222
http://web-scraping.appspot.com/places/default/view/Tajikistan-223
http://web-scraping.appspot.com/places/default/view/Tanzania-224
http://web-scraping.appspot.com/places/default/view/Thailand-225
http://web-scraping.appspot.com/places/default/view/Togo-226
http://web-scraping.appspot.com/places/default/view/Tokelau-227
http://web-scraping.appspot.com/places/default/view/Tonga-228
http://web-scraping.appspot.com/places/default/view/Trinidad-and-Tobago-229
http://web-scraping.appspot.com/places/default/view/Tunisia-230
http://web-scraping.appspot.com/places/default/view/Turkey-231
http://web-scraping.appspot.com/places/default/view/Turkmenistan-232
http://web-scraping.appspot.com/places/default/view/Turks-and-Caicos-Islands-233
http://web-scraping.appspot.com/places/default/view/Tuvalu-234
http://web-scraping.appspot.com/places/default/view/US-Virgin-Islands-235
http://web-scraping.appspot.com/places/default/view/Uganda-236
http://web-scraping.appspot.com/places/default/view/Ukraine-237
http://web-scraping.appspot.com/places/default/view/United-Arab-Emirates-238
http://web-scraping.appspot.com/places/default/view/United-Kingdom-239
http://web-scraping.appspot.com/places/default/view/United-States-240
http://web-scraping.appspot.com/places/default/view/United-States-Minor-Outlying-Islands-241
http://web-scraping.appspot.com/places/default/view/Uruguay-242
http://web-scraping.appspot.com/places/default/view/Uzbekistan-243
http://web-scraping.appspot.com/places/default/view/Vanuatu-244
http://web-scraping.appspot.com/places/default/view/Vatican-245
http://web-scraping.appspot.com/places/default/view/Venezuela-246
http://web-scraping.appspot.com/places/default/view/Vietnam-247
http://web-scraping.appspot.com/places/default/view/Wallis-and-Futuna-248
http://web-scraping.appspot.com/places/default/view/Western-Sahara-249
http://web-scraping.appspot.com/places/default/view/Yemen-250
http://web-scraping.appspot.com/places/default/view/Zambia-251
http://web-scraping.appspot.com/places/default/view/Zimbabwe-252
"""